### ISSUE TITLE
Use latest published version of mosaic.js

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenSTFoundation/brandedtoken.js#113]
Update package.json to use the latest version of mosaic.json

https://www.npmjs.com/package/@openstfoundation/mosaic.js

**Comment by schemar** [comment]
@sarvesh-ost do you require a newer release of moasic.js ?

**Comment by sarvesh-ost** [comment]
I don't think, BrandedToken.js needs anything new from mosaic.js. I will double check.
